#!/usr/bin/env node
// scripts/audit_catalog.mjs
//
// Phase 3 Session 12 — consumes scripts/extraction_output.json (produced by
// extract_answer_keys.mjs) and writes docs/PHASE_3_CATALOG_AUDIT.md with
// every catalog row bucketed into clean / mixed / count-mismatch / unknown
// / missing-key / missing-stu, plus orphan files on disk.
//
// Read-only. No Firestore, no catalog mutations, no network.
//
// Usage:
//   node scripts/audit_catalog.mjs

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, basename, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");
const INPUT_PATH = join(__dirname, "extraction_output.json");
const CATALOG_PATH = join(REPO_ROOT, "worksheets_catalog.json");
const OUT_PATH = join(REPO_ROOT, "docs", "PHASE_3_CATALOG_AUDIT.md");

const ONEDRIVE_ROOTS = [
  "/Users/kiranshay/Library/CloudStorage/OneDrive-Personal/Desktop/Affordable Tutoring Solutions Inc/Official Worksheets & Resources",
  "/Users/kiranshay/Downloads/ats_psms",
  "/Users/kiranshay/Library/CloudStorage/OneDrive-Personal/Desktop/Affordable Tutoring Solutions Inc/Client Profiles",
];

function walk(dir) {
  const out = [];
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return out;
  }
  for (const name of entries) {
    const full = join(dir, name);
    let st;
    try {
      st = statSync(full);
    } catch {
      continue;
    }
    if (st.isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

const norm = (s) => s.toLowerCase().replace(/\s+/g, " ").trim();

function collectDiskPdfs() {
  const keys = new Map(); // normalized -> original basename (first seen)
  const stus = new Map();
  for (const root of ONEDRIVE_ROOTS) {
    for (const path of walk(root)) {
      const base = basename(path);
      const lower = base.toLowerCase();
      if (!lower.endsWith(".pdf")) continue;
      if (lower.startsWith("key_")) {
        const k = norm(base);
        if (!keys.has(k)) keys.set(k, base);
      } else if (lower.startsWith("stu_")) {
        const k = norm(base);
        if (!stus.has(k)) stus.set(k, base);
      }
    }
  }
  return { keys, stus };
}

function tableRow(cells) {
  return "| " + cells.map((c) => String(c ?? "")).join(" | ") + " |";
}

function main() {
  const results = JSON.parse(readFileSync(INPUT_PATH, "utf8"));
  const catalog = JSON.parse(readFileSync(CATALOG_PATH, "utf8"));

  const clean = [];
  const mixed = [];
  const mismatch = [];
  const unknown = [];
  const missingKey = [];
  const missingStu = [];
  const extractionError = [];
  const unsupported = [];

  for (const r of results) {
    if (r.answerFormat === "unsupported") {
      unsupported.push(r);
      continue;
    }
    if (!r.keyFound) missingKey.push(r);
    if (!r.stuFound) missingStu.push(r);
    if (r.extractionError) {
      extractionError.push(r);
      continue;
    }
    if (!r.keyFound) continue;
    if (r.countMismatch) {
      mismatch.push(r);
      continue;
    }
    if (r.answerFormat === "unknown") {
      unknown.push(r);
      continue;
    }
    if (r.answerFormat === "mixed") {
      mixed.push(r);
      continue;
    }
    clean.push(r);
  }

  // Orphan files: on disk but no catalog entry expects them. Normalized
  // comparison so case-variant filenames don't look orphaned.
  const { keys: diskKeys, stus: diskStus } = collectDiskPdfs();
  const expectedKeys = new Set(
    catalog.filter((e) => e.keyTitle).map((e) => norm(`KEY_${e.keyTitle}.pdf`))
  );
  const expectedStus = new Set(
    catalog
      .filter((e) => e.title)
      .map((e) => norm(`STU_${e.stuTitle || e.title}.pdf`))
  );
  const orphanKeys = [...diskKeys.entries()]
    .filter(([k]) => !expectedKeys.has(k))
    .map(([, base]) => base)
    .sort();
  const orphanStus = [...diskStus.entries()]
    .filter(([k]) => !expectedStus.has(k))
    .map(([, base]) => base)
    .sort();

  // Build the markdown report.
  const md = [];
  md.push("# Phase 3 Session 12 — Catalog Audit\n");
  md.push(`**Generated:** 2026-04-14`);
  md.push(
    `**Source of truth:** [scripts/extraction_output.json](../scripts/extraction_output.json), regenerated by \`node scripts/extract_answer_keys.mjs\`.\n`
  );
  md.push("## Source trees\n");
  for (const r of ONEDRIVE_ROOTS) md.push(`- \`${r}\``);
  md.push("");
  md.push(
    "Both trees are indexed together. The live OneDrive mount uses catalog-style abbreviated filenames and is authoritative for most worksheets; the `ats_psms` bulk download uses expanded filenames and contributes worksheets (mostly STU PDFs) the live mount is missing.\n"
  );

  md.push("## Headline numbers\n");
  md.push("| Bucket | Count |");
  md.push("|---|---:|");
  const supported = catalog.length - unsupported.length;
  md.push(tableRow(["Catalog entries", catalog.length]));
  md.push(tableRow(["Supported (excludes unsupported)", supported]));
  md.push(
    tableRow(["KEY PDF found on disk (of supported)", supported - missingKey.length])
  );
  md.push(
    tableRow(["STU PDF found on disk (of supported)", supported - missingStu.length])
  );
  md.push(
    tableRow([
      "**Clean extraction** (pure MC or pure FR, count matches `qs`)",
      `**${clean.length}**`,
    ])
  );
  md.push(tableRow(["Mixed answerFormat (needs triage)", mixed.length]));
  md.push(tableRow(["Q-count mismatch (catalog `qs` ≠ extracted count)", mismatch.length]));
  md.push(tableRow(["Unknown (PDF parsed, zero tuples extracted)", unknown.length]));
  md.push(tableRow(["Extraction error (pdftotext failed)", extractionError.length]));
  md.push(tableRow(["Missing KEY PDF (of supported)", missingKey.length]));
  md.push(tableRow(["Missing STU PDF (of supported)", missingStu.length]));
  md.push(
    tableRow([
      "Unsupported (stubs, Full Length exams, literary prompts)",
      unsupported.length,
    ])
  );
  md.push(tableRow(["Orphan KEY files on disk (no catalog row)", orphanKeys.length]));
  md.push(tableRow(["Orphan STU files on disk (no catalog row)", orphanStus.length]));
  md.push("");

  // § Clean
  md.push(`## Clean extraction (${clean.length})\n`);
  md.push(
    "Worksheets where the KEY PDF parsed cleanly, the extracted question count matches the catalog's `qs`, and every answer fits either pure multiple-choice (A-D) or pure free-response (numeric/fraction). **These are the set that Session 12 commits to Firestore and writes back to the catalog.**\n"
  );
  md.push("| idx | Title | qs | fmt | First 3 tuples |");
  md.push("|---:|---|---:|---|---|");
  for (const r of clean) {
    const firstThree = r.tuples
      .slice(0, 3)
      .map((t) => `${t.questionId}→${t.correctAnswer}`)
      .join(", ");
    md.push(tableRow([r.idx, r.title, r.tuples.length, r.answerFormat, firstThree]));
  }
  md.push("");

  // § Mixed
  md.push(`## Mixed answerFormat — needs triage (${mixed.length})\n`);
  md.push(
    "Worksheets whose extracted answers include at least one string that is neither a clean A-D letter nor a clean numeric/fraction. Possible causes: legitimately mixed MC + grid-in, numeric answers with trailing units, alternative answer formats (`A or 1`), decimal answers, ranges. The **Offending answers** column shows every answer that failed the clean-format check — use it to decide whether to tighten the FR regex for a second pass or accept these as genuinely mixed.\n"
  );
  md.push("| idx | Title | qs | Offending answers |");
  md.push("|---:|---|---:|---|");
  // Same classifier as extract_answer_keys.mjs.
  const FR_PIECE = /^-?(?:\d+(?:\.\d+)?|\.\d+|\d+\/\d+)$/;
  const MC_PIECE = /^[A-D]$/;
  const classify = (raw) => {
    if (!raw) return "null";
    const a = raw.trim();
    if (MC_PIECE.test(a)) return "mc";
    const pieces = a.split(/\s*,\s*/).filter(Boolean);
    if (pieces.length > 0 && pieces.every((p) => FR_PIECE.test(p))) return "fr";
    return "other";
  };
  for (const r of mixed) {
    // Offenders = any answer that's neither pure MC nor pure FR.
    // For true MC+FR mixed worksheets, show an "MC×N / FR×N" summary instead.
    const kinds = r.tuples.map((t) => classify(t.correctAnswer));
    const otherCount = kinds.filter((k) => k === "other").length;
    const mcCount = kinds.filter((k) => k === "mc").length;
    const frCount = kinds.filter((k) => k === "fr").length;
    const offenders = r.tuples
      .filter((t) => classify(t.correctAnswer) === "other")
      .map((t) => t.correctAnswer);
    const uniq = [...new Set(offenders)];
    let display;
    if (otherCount === 0) {
      // True mixed-format worksheet: MC and FR in the same PDF, no offenders.
      display = `**true mixed:** MC×${mcCount} / FR×${frCount}`;
    } else {
      display =
        uniq.length > 8
          ? uniq.slice(0, 8).join(" · ") + ` · +${uniq.length - 8} more`
          : uniq.join(" · ");
    }
    md.push(tableRow([r.idx, r.title, r.tuples.length, display]));
  }
  md.push("");

  // § Count mismatch
  md.push(`## Q-count mismatch (${mismatch.length})\n`);
  md.push(
    "Catalog `qs` disagrees with the number of `Question ID` headers extracted from the PDF. Either the catalog is stale, the PDF has a non-standard layout, or spurious header matches were picked up. Each row shows all extracted tuples so you can eyeball which side is wrong.\n"
  );
  for (const r of mismatch) {
    md.push(`### [${r.idx}] ${r.title}`);
    md.push(`- catalog \`qs\`: **${r.expectedQs}**`);
    md.push(`- extracted tuples: **${r.tuples.length}**`);
    md.push(`- key file: \`${r.keyFile}\``);
    md.push("");
    md.push("| # | questionId | correctAnswer |");
    md.push("|---:|---|---|");
    r.tuples.forEach((t, i) => {
      md.push(tableRow([i, t.questionId, t.correctAnswer ?? "_(null)_"]));
    });
    md.push("");
  }

  // § Unknown
  md.push(`## Unknown — no tuples extracted (${unknown.length})\n`);
  md.push(
    "The KEY PDF was parseable by `pdftotext` but zero `Question ID` headers were found. Likely the PDF uses a different document shape (older College Board releases, hand-written keys, image-only scans). **Punt.**\n"
  );
  md.push("| idx | Title | keyFile |");
  md.push("|---:|---|---|");
  for (const r of unknown) {
    md.push(tableRow([r.idx, r.title, r.keyFile]));
  }
  md.push("");

  // § Extraction errors
  if (extractionError.length) {
    md.push(`## Extraction error (${extractionError.length})\n`);
    md.push("| idx | Title | Error |");
    md.push("|---:|---|---|");
    for (const r of extractionError) {
      md.push(tableRow([r.idx, r.title, r.extractionError]));
    }
    md.push("");
  }

  // § Missing KEY
  md.push(`## Missing KEY PDF (${missingKey.length})\n`);
  md.push(
    "Catalog entries whose expected `KEY_${keyTitle}.pdf` was not found in either source tree. **Triage categories:**\n"
  );
  md.push(
    "- **Fixable by catalog edit** — the file exists under a slightly different name (abbreviation mismatch, spacing, punctuation). Fix `keyTitle` in the catalog.\n- **Fixable by file rename** — the catalog is canonical and the file needs renaming on OneDrive.\n- **Punt** — Full Length Practice Exams, old CB releases, Literary/Poetry subfolders use different document shapes. Punt to post-Session-15 triage.\n"
  );
  md.push("| idx | Title | Expected keyFile |");
  md.push("|---:|---|---|");
  for (const r of missingKey) {
    md.push(tableRow([r.idx, r.title, r.keyFile]));
  }
  md.push("");

  // § Missing STU
  md.push(`## Missing STU PDF (${missingStu.length})\n`);
  md.push(
    "Catalog entries whose expected `STU_${title}.pdf` was not found on disk. `migrate_stu_pdfs.mjs` cannot upload these to Firebase Storage, so their `stu` field stays pointing at the OneDrive `1drv.ms` share link for now.\n"
  );
  md.push("| idx | Title | Expected stuFile |");
  md.push("|---:|---|---|");
  for (const r of missingStu) {
    md.push(tableRow([r.idx, r.title, r.stuFile]));
  }
  md.push("");

  // § Orphan KEY
  md.push(`## Orphan KEY files on disk (${orphanKeys.length})\n`);
  md.push(
    "KEY PDFs in the source trees that no catalog entry points at. Either the catalog needs a new row, or the file is obsolete/duplicate. **Session 12 does not auto-add catalog rows.**\n"
  );
  if (orphanKeys.length) {
    for (const k of orphanKeys) md.push(`- \`${k}\``);
  } else {
    md.push("_(none)_");
  }
  md.push("");

  // § Orphan STU
  md.push(`## Orphan STU files on disk (${orphanStus.length})\n`);
  if (orphanStus.length) {
    for (const s of orphanStus) md.push(`- \`${s}\``);
  } else {
    md.push("_(none)_");
  }
  md.push("");

  // § Unsupported
  md.push(`## Unsupported (${unsupported.length})\n`);
  md.push(
    "Catalog rows that were explicitly marked `answerFormat: \"unsupported\"` by `scripts/apply_catalog_fixes.mjs`. The extractor skips these. They stay in the catalog so future sessions can upgrade them in place if a supported variant becomes available. Buckets:\n"
  );
  md.push(
    "- **Stub rows** — title/keyTitle are literal placeholders (`STU`/`KEY`/`N/A`). Never had real data.\n- **Full Length exam writing sections** — PT1/2/4/5/6/7/8 + April 2019. Section-level answer sheets without per-question `Question ID` headers.\n- **Literary / poetry prompts** — prose writing prompts (Poetry Practice #1-#4, Independent and Dependent Clauses). No objectively gradable answer key.\n"
  );
  md.push("| idx | Title | Reason |");
  md.push("|---:|---|---|");
  for (const r of unsupported) {
    md.push(tableRow([r.idx, r.title, r.unsupportedReason || ""]));
  }
  md.push("");

  md.push("---\n");
  md.push(
    "**Next step:** When the clean-extraction set is acceptable, `extract_answer_keys.mjs --commit` writes `questionKeys/{id}` to Firestore for the clean + true-mixed rows and rewrites `worksheets_catalog.json` with `questionIds[]` + `answerFormat` per row.\n"
  );

  writeFileSync(OUT_PATH, md.join("\n"));
  console.log(`[audit] wrote ${OUT_PATH}`);
  console.log(`[audit]   clean:         ${clean.length}`);
  console.log(`[audit]   mixed:         ${mixed.length}`);
  console.log(`[audit]   count-mismatch:${mismatch.length}`);
  console.log(`[audit]   unknown:       ${unknown.length}`);
  console.log(`[audit]   missing KEY:   ${missingKey.length}`);
  console.log(`[audit]   missing STU:   ${missingStu.length}`);
  console.log(`[audit]   unsupported:   ${unsupported.length}`);
  console.log(`[audit]   orphan KEY:    ${orphanKeys.length}`);
  console.log(`[audit]   orphan STU:    ${orphanStus.length}`);
}

main();
